version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./test.db
    volumes:
      - ./backend/app:/app
  
  frontend:
    build: ./frontend
    ports:
      - "3000:5000"  # 'serve' por defecto corre en 5000
    depends_on:
      - backend
